# root-app.yaml (Create this file locally, NOT in your Git repo yet)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root-app # A name for the watcher app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sarabadu/gitops.git # The same repo URL you used before
    targetRevision: HEAD
    # Point the path to the directory where your Application YAMLs are stored
    path: .argocd/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # This app deploys into the argocd namespace (it deploys the Application CRDs)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
